trigger:
- main

pool:
  name: Azure Pipelines

steps:


- task: Docker@2
  inputs:
    containerRegistry: 'acrado7'
    repository: 'azurewebapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)


- script: |
    sed -i 's/<TAG>/$(Build.BuildId)/' $(Build.SourcesDirectory)/deployment.yaml
  displayName: 'Update Image Tag in Deployment Manifest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aksado07-default'
    namespace: 'default'
    manifests: |
      $(Build.SourcesDirectory)/deployment.yaml
      $(Build.SourcesDirectory)/service.yaml